void numinue_cosbeta()
{
//=========Macro generated from canvas: c/
//=========  (Tue Jul 13 11:30:18 2021) by ROOT version 6.18/04
   TCanvas *c = new TCanvas("c", "",1,1,500,476);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->Range(-1.405405,-3.4375e-39,1.297297,2.78125e-38);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.15);
   c->SetFrameBorderMode(0);
   c->SetFrameBorderMode(0);
   Double_t xAxis9[6] = {-1, 0.6, 0.79, 0.9, 0.95, 1}; 
   
   TH1D *MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9 = new TH1D("MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9","3.4349",5, xAxis9);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetBinContent(1,7.799058e-40);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetBinContent(2,4.042292e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetBinContent(3,6.699302e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetBinContent(4,1.29049e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetBinContent(5,1.776283e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetBinError(1,1.326123e-42);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetBinError(2,7.538154e-42);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetBinError(3,1.299187e-41);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetBinError(4,2.372508e-41);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetBinError(5,2.833253e-41);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetMinimum(0);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetMaximum(2.5e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetEntries(1267689);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = 1437;
   color = new TColor(ci, 0, 0, 0.8, " ", 0.5);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetFillColor(ci);

   ci = TColor::GetColor("#0000cc");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetLineColor(ci);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->SetLineWidth(2);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetXaxis()->SetTitle("cos#beta_{e}^{true}");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetXaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetXaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetXaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetXaxis()->SetTitleOffset(1);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetXaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetYaxis()->SetTitle("d#sigma/dcos#beta_{e}^{true} (cm^{2}/GeV/nucleon)");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetYaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetYaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetYaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetYaxis()->SetTitleOffset(1.3);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetYaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetZaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetZaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetZaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetZaxis()->SetTitleOffset(1);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->GetZaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__9->Draw("hist e3 l");
   Double_t xAxis10[6] = {-1, 0.6, 0.79, 0.9, 0.95, 1}; 
   
   TH1D *MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10 = new TH1D("MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10","3.5552",5, xAxis10);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetBinContent(1,8.236568e-40);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetBinContent(2,4.26828e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetBinContent(3,7.049923e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetBinContent(4,1.359559e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetBinContent(5,1.875636e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetBinError(1,1.655338e-42);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetBinError(2,9.40706e-42);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetBinError(3,1.624356e-41);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetBinError(4,2.971954e-41);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetBinError(5,3.559421e-41);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetMinimum(0);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetMaximum(2.5e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetEntries(901642);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetStats(0);

   ci = 1438;
   color = new TColor(ci, 0.8, 0, 0, " ", 0.5);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetFillColor(ci);

   ci = TColor::GetColor("#cc0000");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetLineColor(ci);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->SetLineWidth(2);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetXaxis()->SetTitle("cos#beta_{e}^{true}");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetXaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetXaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetXaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetXaxis()->SetTitleOffset(1);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetXaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetYaxis()->SetTitle("d#sigma/dcos#beta_{e}^{true} (cm^{2}/GeV/nucleon)");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetYaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetYaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetYaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetYaxis()->SetTitleOffset(1.3);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetYaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetZaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetZaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetZaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetZaxis()->SetTitleOffset(1);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->GetZaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__10->Draw("hist e3 l same");
   Double_t xAxis11[6] = {-1, 0.6, 0.79, 0.9, 0.95, 1}; 
   
   TH1D *MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11 = new TH1D("MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11","4.0861",5, xAxis11);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetBinContent(1,8.917467e-40);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetBinContent(2,4.654704e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetBinContent(3,6.860631e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetBinContent(4,1.349824e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetBinContent(5,1.965763e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetBinError(1,6.176245e-41);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetBinError(2,4.687276e-40);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetBinError(3,4.608842e-40);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetBinError(4,7.376165e-40);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetBinError(5,1.233683e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetMinimum(0);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetMaximum(2.5e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetEntries(911.8574);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetStats(0);

   ci = 1439;
   color = new TColor(ci, 1, 0.6, 0.2, " ", 0.5);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetLineColor(ci);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->SetLineWidth(2);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetXaxis()->SetTitle("cos#beta_{e}^{true}");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetXaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetXaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetXaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetXaxis()->SetTitleOffset(1);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetXaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetYaxis()->SetTitle("d#sigma/dcos#beta_{e}^{true} (cm^{2}/GeV/nucleon)");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetYaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetYaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetYaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetYaxis()->SetTitleOffset(1.3);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetYaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetZaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetZaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetZaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetZaxis()->SetTitleOffset(1);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->GetZaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__11->Draw("hist e3 l same");
   Double_t xAxis12[6] = {-1, 0.6, 0.79, 0.9, 0.95, 1}; 
   
   TH1D *MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12 = new TH1D("MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12","3.4349",5, xAxis12);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetBinContent(1,7.799058e-40);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetBinContent(2,4.042292e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetBinContent(3,6.699302e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetBinContent(4,1.29049e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetBinContent(5,1.776283e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetBinError(1,1.326123e-42);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetBinError(2,7.538154e-42);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetBinError(3,1.299187e-41);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetBinError(4,2.372508e-41);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetBinError(5,2.833253e-41);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetMinimum(0);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetMaximum(2.5e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetEntries(1267689);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetDirectory(0);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetStats(0);

   ci = TColor::GetColor("#0000cc");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetLineColor(ci);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->SetLineWidth(2);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetXaxis()->SetTitle("cos#beta_{e}^{true}");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetXaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetXaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetXaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetXaxis()->SetTitleOffset(1);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetXaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetYaxis()->SetTitle("d#sigma/dcos#beta_{e}^{true} (cm^{2}/GeV/nucleon)");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetYaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetYaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetYaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetYaxis()->SetTitleOffset(1.3);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetYaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetZaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetZaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetZaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetZaxis()->SetTitleOffset(1);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->GetZaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__12->Draw("hist l same");
   Double_t xAxis13[6] = {-1, 0.6, 0.79, 0.9, 0.95, 1}; 
   
   TH1D *MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13 = new TH1D("MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13","3.5552",5, xAxis13);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetBinContent(1,8.236568e-40);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetBinContent(2,4.26828e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetBinContent(3,7.049923e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetBinContent(4,1.359559e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetBinContent(5,1.875636e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetBinError(1,1.655338e-42);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetBinError(2,9.40706e-42);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetBinError(3,1.624356e-41);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetBinError(4,2.971954e-41);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetBinError(5,3.559421e-41);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetMinimum(0);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetMaximum(2.5e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetEntries(901642);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetDirectory(0);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetStats(0);

   ci = TColor::GetColor("#cc0000");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetLineColor(ci);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->SetLineWidth(2);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetXaxis()->SetTitle("cos#beta_{e}^{true}");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetXaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetXaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetXaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetXaxis()->SetTitleOffset(1);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetXaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetYaxis()->SetTitle("d#sigma/dcos#beta_{e}^{true} (cm^{2}/GeV/nucleon)");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetYaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetYaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetYaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetYaxis()->SetTitleOffset(1.3);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetYaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetZaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetZaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetZaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetZaxis()->SetTitleOffset(1);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->GetZaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__13->Draw("hist l same");
   Double_t xAxis14[6] = {-1, 0.6, 0.79, 0.9, 0.95, 1}; 
   
   TH1D *MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14 = new TH1D("MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14","4.0861",5, xAxis14);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetBinContent(1,8.917467e-40);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetBinContent(2,4.654704e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetBinContent(3,6.860631e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetBinContent(4,1.349824e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetBinContent(5,1.965763e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetBinError(1,6.176245e-41);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetBinError(2,4.687276e-40);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetBinError(3,4.608842e-40);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetBinError(4,7.376165e-40);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetBinError(5,1.233683e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetMinimum(0);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetMaximum(2.5e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetEntries(911.8574);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetDirectory(0);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetStats(0);

   ci = TColor::GetColor("#ff9933");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetLineColor(ci);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->SetLineWidth(2);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetXaxis()->SetTitle("cos#beta_{e}^{true}");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetXaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetXaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetXaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetXaxis()->SetTitleOffset(1);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetXaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetYaxis()->SetTitle("d#sigma/dcos#beta_{e}^{true} (cm^{2}/GeV/nucleon)");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetYaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetYaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetYaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetYaxis()->SetTitleOffset(1.3);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetYaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetZaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetZaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetZaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetZaxis()->SetTitleOffset(1);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->GetZaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC__14->Draw("hist l same");
   Double_t xAxis15[6] = {-1, 0.6, 0.79, 0.9, 0.95, 1}; 
   
   TH1D *h_run1_CV_0_true_el_cang_mc_xsec__15 = new TH1D("h_run1_CV_0_true_el_cang_mc_xsec__15","",5, xAxis15);
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetBinContent(1,7.902113e-40);
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetBinContent(2,4.107951e-39);
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetBinContent(3,6.890042e-39);
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetBinContent(4,1.325645e-38);
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetBinContent(5,1.808402e-38);
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetBinError(1,2.462037e-41);
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetBinError(2,1.147615e-40);
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetBinError(3,2.023029e-40);
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetBinError(4,3.279094e-40);
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetBinError(5,3.854558e-40);
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetEntries(6767.803);
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetStats(0);
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetOption("hist");
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetLineStyle(7);
   h_run1_CV_0_true_el_cang_mc_xsec__15->SetLineWidth(2);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetXaxis()->SetTitle("cos#beta^{true}_{e}");
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetXaxis()->SetLabelFont(132);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetXaxis()->SetLabelSize(0.05);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetXaxis()->SetTitleSize(0.05);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetXaxis()->SetTitleOffset(1);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetXaxis()->SetTitleFont(132);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetYaxis()->SetTitle("#frac{d#sigma}{dcos#beta^{true}_{e}} [10^{-39} cm^{2}/nucleon]");
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetYaxis()->SetLabelFont(132);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetYaxis()->SetLabelSize(0.05);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetYaxis()->SetTitleSize(0.05);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetYaxis()->SetTitleOffset(1.3);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetYaxis()->SetTitleFont(132);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetZaxis()->SetLabelFont(132);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetZaxis()->SetLabelSize(0.05);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetZaxis()->SetTitleSize(0.05);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetZaxis()->SetTitleOffset(1);
   h_run1_CV_0_true_el_cang_mc_xsec__15->GetZaxis()->SetTitleFont(132);
   h_run1_CV_0_true_el_cang_mc_xsec__15->Draw("hist l same");
   Double_t xAxis16[6] = {-1, 0.6, 0.79, 0.9, 0.95, 1}; 
   
   TH1D *MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16 = new TH1D("MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16","MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue",5, xAxis16);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetBinContent(1,8.294005e-40);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetBinContent(2,2.800233e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetBinContent(3,8.455849e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetBinContent(4,1.299344e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetBinContent(5,1.754787e-38);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetBinError(1,2.32251e-40);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetBinError(2,1.280216e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetBinError(3,2.063984e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetBinError(4,3.843315e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetBinError(5,4.163888e-39);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetEntries(47.7391);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetDirectory(0);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetStats(0);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetLineWidth(2);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetMarkerStyle(20);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->SetMarkerSize(0.75);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetXaxis()->SetTitle("cos#beta_{e}^{true}");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetXaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetXaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetXaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetXaxis()->SetTitleOffset(1);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetXaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetYaxis()->SetTitle("d#sigma/dcos#beta_{e}^{true} (cm^{2}/GeV/nucleon)");
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetYaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetYaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetYaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetYaxis()->SetTitleOffset(1.3);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetYaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetZaxis()->SetLabelFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetZaxis()->SetLabelSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetZaxis()->SetTitleSize(0.05);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetZaxis()->SetTitleOffset(1);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->GetZaxis()->SetTitleFont(132);
   MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data__16->Draw("e1 same");
   
   TLegend *leg = new TLegend(0.2,0.6,0.73,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(132);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC","GENIE v3.00.06, #chi^{2}/dof=3.4/5","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000cc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC","NuWro 19.02.1, #chi^{2}/dof=3.6/5","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cc0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_MC","GiBUU 2019.08, #chi^{2}/dof=4.1/5","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("h_run1_CV_0_true_el_cang_mc_xsec","GENIE v3 MC","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(7);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("MicroBooNE_CCInc_NuMI_XSec_1DCosBeta_nue_data","Data","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.75);
   entry->SetTextFont(132);
   leg->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
